### ISSUE TITLE
Agendamentos

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#12]
## Descrição
Aborda os agendamentos realizados pelos moradores.

- [x] layout da listagem
- [x] botão para cadastro
- [x] layout do cadastro
- [x] campos requisitados no cadastro
- [x] procurar um agendamento
- [x] operações de editar/deletar
- [x] mostrar nome do morador na listagem e visualização

## Branch
https://github.com/falso-de-verdade/web/tree/develop

**Comment by marcavis** [comment]
Penso que a tela Agendamentos deveria ter uma coluna a mais na visualização do síndico - uma coluna referente ao morador que reservou a dependência.
No caso da visualização do morador, é implícito que ele próprio fez a reserva.

**Comment by marquesYan** [comment]
Foi adicionado também o nome do morador ao visualizar um agendamento.
