### ISSUE TITLE
Condomínios

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#13]
#### Descrição
Aborda os condomínios tanto dos moradores quanto dos síndicos. A diferença seria que o morador não é capaz de editar ou criar um novo.

 - [x] layout da listagem
- [x] botão para cadastro
- [x] layout do cadastro
- [x] campos requisitados no cadastro
- [x] procurar um condomínio
- [x] operações de alterar/deletar
- [x] remover cadastro de imagens.

## Branch
https://github.com/falso-de-verdade/web/tree/feat-condominium

**Comment by marquesYan** [comment]
- [ ] remover cadastro de imagens.

**Comment by marquesYan** [comment]
Obs: segundo o rf nº 4, o condomínio aceitaria imagens no cadastro, sendo assim, será necessário atualizar este requisito.

**Comment by marcavis** [comment]
Na tela "Novo condomínio, ao se clicar "Cancelar", a rota está incorreta, direcionando para a página inexistente
http://localhost:3000/condominiums
em vez de
http://localhost:3000/admin/condominiums
