### ISSUE TITLE
Conflitos

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#14]
## Descrição
Aborda os conflitos gerados pelos moradores para a ocupação de uma dependência já agendada.

- [x] layout da listagem
- [x] procurar um conflito
- [x] mostrar os dados do agendamento referente a um conflito
- [x] listar os moradores que possuem um ticket para o agendamento em questão
- [x] operação de resolução do conflito e botão para visualização de um conflito na listagem
- [x] mostrar total de solicitantes de um conflito na visualização deste
- [x] listar os agendamentos envolvidos no conflito
- [x] mostrar dependência na listagem

## Branch
https://github.com/falso-de-verdade/web/tree/feat-collisions

**Comment by marquesYan** [comment]
Questões discutidas:
 - deixar um botão para visualização
 - colocar o botão na esquerda ou direita?

**Comment by marcavis** [comment]
A visualização de um conflito específico (http://localhost:3000/admin/collision/teste1/)
possui uma aba "dados do agendamento" que mostra uma informação supostamente comum aos tickets participantes do conflito, mas esse não seria o caso - os dois agendamentos em conflito poderiam ter pedido horários diferentes, porém parcialmente incompatíveis (8 às 14 vs. 10 às 16)

Na lista de conflitos (http://localhost:3000/admin/collisions) pode ser interessante adicionar uma coluna que mostre a quantidade de solicitantes OU o nome destes; pode ser impraticável se uma grande quantidade de moradores fizer parte do conflito.
