### ISSUE TITLE
Agendamento de reuniões

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#15]
## Descrição
Aborda a situação de o síndico realizar o agendamento de reuniões de condomínio/prédio/etc.

- [x] layout da listagem
- [x] procurar por uma reunião (filtrando por data? realidas? pendentes?)
- [x] layout do cadastro
- [x] botão para cadastro
- [x] campos requisitados no cadastro
- [x] operações de editar/cancelar

**Comment by GusMartins499** [comment]
branch feat-condominium-meetings

**Comment by marcavis** [comment]
http://localhost:3000/admin/meetings/
1) Pendente -> Pendentes no drop down de filtro de reuniões;
2) A página de listagem de reuniões conter um formulário de criação de nova reunião agrega agilidade, porém é inconsistente com a experiência de usuário das outras páginas; a página pode ficar visualmente "ocupada demais" quando houverem várias reuniões já agendadas.

**Comment by GusMartins499** [comment]
Transformado o form em uma nova rota, alterado o texto do dropdown. Alterações feitas na mesma branch.

branch feat-condominium-meetings

**Comment by marquesYan** [comment]
Items faltando:
 - botão na listagem para adicionar reunião
 - botão para salvar e cancelar na visualização ou criação de uma reunião

**Comment by marcavis** [comment]
Agendar nova reunião: o campo Duração deveria definir qual unidade espera do usuário - minutos? horas?
