### ISSUE TITLE
Configurações de usuário

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#17]
## Descrição
Aborda a parte voltado ao usuário, como atualização de dados pessoais.

- [ ] layout para as configurações
- [ ] atualização de campos requisitados do usuário em questão

## Dependência
#16

**Comment by GusMartins499** [comment]
Seguindo o que está nos requisitos, (requisito funcional nº 17), todos os 3 campos foram criados, junto com um formulário e 2 botões, gravar e cancelar

**Comment by GusMartins499** [comment]
Revisão se será somente esses campos. (até o momento não foi revisado)  - 22/09

**Comment by GusMartins499** [comment]
Sugestão: Dropdown ao lado do logout
