### ISSUE TITLE
Escopo de visão

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#18]
## Descrição
Aborda um item que possibilite escolher um condomínio para ser usado como escopo. Quando um condomínio está selecionado no escopo de visão, apenas os moradores, dependências, conflitos e reuniões do condomínio em escopo serão mostrados.

- [x] item para a escolha opcional do condominio
~- [ ] remover select nas rotas PUT~

## Branch
https://github.com/falso-de-verdade/web/tree/develop

**Comment by GusMartins499** [comment]
A princípio está no Header da aplicação com dados estáticos.

**Comment by GusMartins499** [comment]
Um detalhe que acabei de perceber, nas rotas de PUT, essa opção não pode estar visível. Tenho que fazer o ajuste depois.

**Comment by GusMartins499** [comment]
> ## Descrição
> Aborda um item que possibilite escolher um condomínio para ser usado como escopo. Quando um condomínio está selecionado no escopo de visão, apenas os moradores, dependências, conflitos e reuniões do condomínio em escopo serão mostrados.
> 
> * [x]  item para a escolha opcional do condominio
> * []  Remover opção nas rotas PUT

**Comment by marcavis** [comment]
Provavelmente não deveria ser permitido selecionar a opção "Selecione o condomínio" - trabalhar na ausência de condomínio selecionado não faz muito sentido

**Comment by heitordarela** [comment]
Creio que não é necessário ao abrir o dropdown ter o "título" **condomínios** que está em negrito, pois já existe a mensagem "Selecione o condomínio"  e não teria outro tipo de coisa para selecionas, somente condomínios.

**Comment by marquesYan** [comment]
> Creio que não é necessário ao abrir o dropdown ter o "título" **condomínios** que está em negrito, pois já existe a mensagem "Selecione o condomínio" e não teria outro tipo de coisa para selecionar, somente condomínios.

Talvez colocar o `Selecione o condomínio` como o placeholder do select.
