### ISSUE TITLE
Botão de criar conta está sem ícone

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#20]
## Descrição
O botão para criar uma conta do síndico em "/login" está com um ícone errado.

**Comment by marcavis** [comment]
Sugiro
fa fa-user-plus
ou
fa fa-address-card

**Comment by GusMartins499** [comment]
Ajustado
branch: UX-icon-button-new-account

**Comment by GusMartins499** [comment]
feito o merge com a develop
