### ISSUE TITLE
Melhorar campo que seleciona condomínio de escopo

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#25]
## Descrição
Remover opção do campo `Selecione o condomínio` e o título `condomínios` que está em negrito.

## Referencia
#18

**Comment by GusMartins499** [comment]
Ajustado.
branch:  UX-removinf-option-select-condominium
ps: é, escrevi errado mesmo 👍

**Comment by GusMartins499** [comment]
Feito o merge com a branch develop
