### ISSUE TITLE
Tickets do Morador

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#27]
## Descrição
Aborda os tickets aberto pelo morador.

- [x] layout da listagem
- [x] layout de visualização
- [x] informar ao usuário quando um agendamento criado criou um ticket  
- [x] operações de visualizar/cancelar

## Branch
feat-tickets

**Comment by marcavis** [comment]
Consideração que está talvez fora do escopo da análise desta issue: para um morador, parece ser complexo haver uma página de Agendamentos e outra de Tickets - talvez tudo deva ser mostrado na mesma página?
Um morador raramente terá vários agendamentos pendentes de tratamento, penso.

Página tickets contém um botão "+" para criar novo ticket, que talvez seja dispensável - tickets são criados automaticamente quando há conflitos de agendamentos.

**Comment by marquesYan** [comment]
Será removido o botão para criar um novo ticket. (Devo ter me esquecido de tirá-lo)
