### ISSUE TITLE
Cadastro de morador e síndico devem lidar com contas pré-existentes

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#31]
## Descrição
Ao receber um convite para virar morador de um condomínio ou no cadastro de síndico, é apresentado uma página onde, por padrão, é mostrado campos de email, senha, e confirma senha; porém, deve ser apresentado (um botão, ou talvez o lado direito da tela) uma opção "Já tenho conta", onde o usuário faz um login normal, aceitando o convite.

## Branch
feat-existing-account

**Comment by marcavis** [comment]
Botão "Usar conta existente" parece estar com erro de posicionamento; não encontrei nada a reclamar no funcionamento.

**Comment by marquesYan** [comment]
> Botão "Usar conta existente" parece estar com erro de posicionamento; não encontrei nada a reclamar no funcionamento.

Sim, o design está fora de esquadro. Vou finalizar essa issue, levando em consideração o seu funcionamento, e vou abrir uma issue para melhorar os botões.
