### ISSUE TITLE
Escolha de papel do usuário no acesso ao sistema

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#32]
## Descrição
No login, se o usuário que foi autenticado possui dois usuários com papéis diferentes, síndico e morador, então deve ser apresentado uma seção para escolher qual papel usar para a sessão atual.

## Referência
https://nubank.com.br/en/business-account/

## Branch
feat-choose-account-role

**Comment by marcavis** [comment]
Implementação está boa, mas talvez devamos considerar renomear "Papéis" para "Perfis"?

"Esta conta possui o papel de síndico de morador. Escolha qual deseja usar."
corrigir para
"Esta conta possui papéis(ou perfis) de síndico e de morador. Escolha qual deseja usar."

**Comment by marquesYan** [comment]
Concordo que fica melhor.
