### ISSUE TITLE
Informar qual o condomínio no convite de morador

### ISSUE THREAD

**Issue by marquesYan** [falso-de-verdade/web#35]
## Descrição
Ao receber o convite ser um morador, além do formulário de cadastro, deve ser apresentado também qual o condomínio de destino do morador.

## Dependência
#31 

## Branch
feat-resident-invite-condominium

**Comment by marcavis** [comment]
Não consegui verificar - já está implementado nessa branch?

**Comment by marquesYan** [comment]
Está sim. Entra na url: `/ResidentRegistration`
