### ISSUE TITLE
Vocabulário: "Ticket"

### ISSUE THREAD

**Issue by marcavis** [falso-de-verdade/web#36]
Penso que a palavra "ticket" deve ser substituída em toda a interface; a palavra é usada tanto para agendamentos quanto conflitos de agendamentos, e, por ser também um termo técnico (neste escopo), causa alguma ambiguidade.

**Comment by GusMartins499** [comment]
Ignorada pois não terá mais a tela de tickets, segue a ISSUE de referência
[#40 ](https://github.com/falso-de-verdade/web/issues/40)
